# This is build in https://dev.azure.com/RichCorner/DevOpsInfrastructures/
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: GenerateAgentImageCreds
  - name: location
    value: 'eastasia'
  - name: imageName
    value: 'ubuntu-22.04'
  - name: ImageResourceGroupName
    value: 'My-DevOps-Agent-OS-Images-RG'

jobs:
  - job: CloneRunnerImage
    displayName: Clone GitHub Runner Image Repo
    steps:
      - script: git clone https://github.com/actions/runner-images.git
        displayName: 'Clone Repo'
        failOnStderr: false
        workingDirectory: '$(Pipeline.Workspace)'

      - task: Bash@3
        displayName: "Dump environment variables and list files"
        inputs:
          workingDirectory: '$(Pipeline.Workspace)'
          targetType: inline
          script: |
            printenv
            ls -la
      
      - script: |
          az group create --name $(ImageResourceGroupName) --location eastasia
        displayName: 'Create Resource Group'
        failOnStderr: false

      - script: |
          packer init -upgrade images/ubuntu/templates/ubuntu-22.04.pkr.hcl
        displayName: 'Initialize packer'
        failOnStderr: false
        workingDirectory: '$(Pipeline.Workspace)/runner-images'

      - script: |
          packer build -var "subscription_id=$(SubscriptionId)" \
             -var "client_id=$(ClientId)" \
             -var "client_secret=$(ClientSecret)" \
             -var "location=$(location)" \
             -var "managed_image_name=$(ImageName)" \
             -var "managed_image_resource_group_name=$(ImageResourceGroupName)" \
             -var "tenant_id=$(TenantId)" \
             "images/ubuntu/templates/ubuntu-22.04.pkr.hcl"
        displayName: 'Build image'
        failOnStderr: false
        workingDirectory: '$(Pipeline.Workspace)/runner-images'
